export const getFitnessTracker = (t: (key: string) => string) => [
  {
    id: 1,
    title: t("home.caloriesBurned"),
    icon: { name: "flame", color: "#EF4444", bg: "bg-red-100" },
    currentValue: 500,
    targetValue: 2000,
    unit: "kcal",
    type: "linear",
  },
  {
    id: 2,
    title: t("home.stepsTaken"),
    icon: { name: "walk", color: "#3B82F6", bg: "bg-blue-100" },
    description: t("home.stepsDescription"),
    type: "status",
  },
  {
    id: 3,
    title: t("home.nutrition"),
    icon: { name: "nutrition", color: "#10B981", bg: "bg-green-100" },
    tags: [t("home.vitaminA"), t("home.ibuprofen"), "2x"],
    type: "tags",
  },
  {
    id: 4,
    title: t("home.sleep"),
    icon: { name: "moon", color: "#8B5CF6", bg: "bg-purple-100" },
    currentValue: 11,
    targetValue: 36,
    unit: t("home.monthlyCircadian"),
    progress: 0.25,
    type: "circular",
  },
  {
    id: 5,
    title: t("home.hydration"),
    icon: { name: "water", color: "#3B82F6", bg: "bg-blue-100" },
    currentValue: 700,
    targetValue: 2000,
    unit: "ml",
    type: "linear",
  },
];
