
auth.token=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

defaults.org=fpt-university-gr
defaults.project=hi-vision-app

defaults.url=https://sentry.io/
